### ISSUE TITLE
Source image webview fails to correctly set scale and function

### ISSUE THREAD

**Issue by raywiis** [raywiis/vscode-image-diff#1]
I know it sucks.
Seems to happen to bigger images that take a while to load in.

**Comment by raywiis** [comment]
@raywiis 
Cool, maybe I'll fix it sometime. Or you could too!

**Comment by bersbersbers** [comment]
Is that the problem that the scale cannot be set to less than 1.2531? This is what I am often observing. Yes, it sucks :)

**Comment by raywiis** [comment]
@bersbersbers Might be. But if you can scale the image at all then it's not the same issue.
Min scale is actually based on the viewport to image ratio is when you open the image.
vscode's default image viewer seemed to stretch the image. So I did the same thing with my min scale.

**Comment by raywiis** [comment]
@bersbersbers do you think the scale should always allow to go to 1?

**Comment by bersbersbers** [comment]
> @bersbersbers Might be. But if you can scale the image at all

Yes, I can *increase* the scale just fine.

> Min scale is actually based on the viewport to image ratio is when you open the image.

I would agree that this *may* make sense for the initial scale, but not the min scale. Actually, I wonder why there is a min scale at all ;)

> vscode's default image viewer seemed to stretch the image. So I made min scale be full width or height of the image in the viewport.

Maybe that part is not fully working then. I often have snapshots that open at 1.2531, extend beyond the bottom, and there is no way to rescale them to see them in full. Usually I have to close the terminal or something.

> @bersbersbers do you think the scale should always allow to go to 1?

I'd say yes. And smaller, too. People may be opening arbitrarily large images. As a rule of thumb, since this extension is replacing VS Code's own viewer and it is hard to switch back and forth between the two, I'd say all basic features of that internal viewer should be replicated.

My feeling is that even the scale should be 1. I often look at GUI snapshots and any scale greater than 1 makes them appear rather unpleasant.

**Comment by raywiis** [comment]
@bersbersbers From what you're saying it might be a bug then :thinking: 
If the image is very large it should take up the whole viewport and scale should be adjusted to below 1 to fit everything in.

**Comment by bersbersbers** [comment]
Looks like it. I will investigate a bit more later, but I think I remember I cannot pan, either. Maybe those two are related.

**Comment by raywiis** [comment]
@bersbersbers Pan is also limited to not allow the image to leave the edge. To prevent panning out the image out of viewport. 
Perhaps an option to allow panning out is better and to just add a reset button somewhere. Or it's just a non problem since it resets when you open the image again.

**Comment by raywiis** [comment]
It's also convenient to zoom out completely and have the image reset.

**Comment by raywiis** [comment]
Might be I don't remember the scale when the original issue happens, but it usually happens when vscode tries to restore a previous session with a diff. One of the diff views doesn't start up properly.

**Comment by raywiis** [comment]
@bersbersbers I've added an option in 0.0.15 to always have 1 as the minimum scale. It's called `Min Scale One` you'll find it in settings if you search.
Check out if it's what you're looking for.

Also I found out there's a command to toggle the editor type, look for `View: Toggle Editor Type`. It should enable the built in image viewer. You can toggle again to easily compare.

**Comment by bersbersbers** [comment]
> @bersbersbers I've added an option in 0.0.15 to always have 1 as the minimum scale. It's called `Min Scale One` you'll find it in settings if you search. Check out if it's what you're looking for.

Yes, that helps a lot! Thanks!

> Also I found out there's a command to toggle the editor, look for `View: Toggle Editor Type`. It should enable the built in image viewer. You can toggle again to easily compare.

That command one I don't see. Also I hardly find it on Google: https://www.google.com/search?q=%22view%3A+toggle+editor+type%22
Where did you find this?

**Comment by raywiis** [comment]
@bersbersbers Cool to hear.

> That command one I don't see. Also I hardly find it on Google: https://www.google.com/search?q=%22view%3A+toggle+editor+type%22
> Where did you find this?

It's in the commands (ctrl/cmd+shift+p), but it only seems to work when you're not looking at a diff.
![image](https://github.com/raywiis/vscode-image-diff/assets/1339015/993b4dad-fc10-453d-b94a-1897cae6548a)

**Comment by bersbersbers** [comment]
> it only seems to work when you're not looking at a diff

I see. That makes it hard to switch the diff view from the extension-provided one to the integrated one, I guess :) but it's fine, with the extension getting better and better, there will be no point any more to switch back at all.

**Comment by raywiis** [comment]
I think I actually found why the original issue happens. It was just a case of not waiting for the image to load into editor webview. There turns out to be a division from `0`, an invalid transformation attempted on the peer image and the whole script poops out with an error.

Anyways. It should be fixed with 0.0.19. More attention to math will be needed.
