### ISSUE TITLE
Feature request: (add option to) always enable diff

### ISSUE THREAD

**Issue by bersbersbers** [raywiis/vscode-image-diff#10]
I could save hundreds of clicks per day if a new diff window had [x] Diff auto-checked.

Thanks!

**Comment by raywiis** [comment]
Seems simple enough, will add when I find a free hour :+1:

**Comment by raywiis** [comment]
It's now be an option from 0.0.24
![image](https://github.com/raywiis/vscode-image-diff/assets/1339015/c9ec04bd-3ce9-45ed-874c-73cd43a6a742)

**Comment by bersbersbers** [comment]
Beautiful, thank you!
