### ISSUE TITLE
Feature request: enable diffs despite size mismatch

### ISSUE THREAD

**Issue by bersbersbers** [raywiis/vscode-image-diff#4]
When two images are of different size, it can still make sense to diff them. Would it be possible to extend the smaller dimensions to the larger ones by padding, so as to enable diffing in this case?

**Comment by raywiis** [comment]
Howdy.
I think it's possible. Would padding being equal on all sides work for you? Could also add additional options to only pad one side.

**Comment by bersbersbers** [comment]
Most of my images are snapshots of GUIs that extend to the bottom right if the content size changes. So having the padding bottom-right-only (or configurable) would be ideal for my use case.

**Comment by raywiis** [comment]
So I've added diffs for different size images on v0.0.11
 It's not quite _complete_. Images are padded out with transparent pixels right and bottom if short.
Hopefully this will help for the time being while I have time to add options or find issues.

**Comment by bersbersbers** [comment]
That's great already, thanks :)

**Comment by raywiis** [comment]
Added a dropdown with said options if the need arises. Default will remain top-left.
Closing this issue but eventually I do think there should be settings for changing the default align and a better UI.
For the future tho.
