### ISSUE TITLE
Stacked swipe or onion skin mode

### ISSUE THREAD

**Issue by dsmmcken** [raywiis/vscode-image-diff#9]
Would love an onion skin or swipe mode where the images are stacked and you can switch between them. Sometimes that's the easiest way to compare.

Like how a github PR does it:
![image](https://github.com/raywiis/vscode-image-diff/assets/1576283/87a5c6a3-9735-4095-881a-6d74fef31250)

**Comment by raywiis** [comment]
I agree with the swipe. Seems like a useful thing to have. Onion skin, at least for me, rarely makes sense so I'd put it lower.

For swipe it might be impossible to show a single webview on vscode when trying to open a diff. That could make it that you need to click a button or shortcut to open another view with swipe controls. 
OR I had this idea of using the view divider in vscode as a sort of slider.

Or vscode has better support for webviews in diff. But I wouldn't count on that

**Comment by dsmmcken** [comment]
> OR I had this idea of using the view divider in vscode as a sort of slider.

That's a crazy idea, I like it.

Thanks for the plugin!

**Comment by raywiis** [comment]
@dsmmcken Added a WIP swipe mode with the divider. You can enable it with the `Toggle swipe mode` command.

It's not perfect - zoom and pan limits make it that left or right image isn't positioned correctly but it should mostly work.
Still planning on fixing any issues that I see.

**Comment by raywiis** [comment]
0.0.27 removes pan bounds when in swipe to make it usable. Don't loose your image off screen :wink:

**Comment by raywiis** [comment]
Closing as I don't want to change anything that's specific for this mode
